version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
     - checkout
     - run: npm install
     - setup_remote_docker:
        docker_layer_caching: true
     - run:
               name: Python version
               command: |
                 sudo apt-get update && sudo apt-get install -y python-pip libpython-dev
                 python -V
     - run:
          name: Install dependencies
          command: |
            sudo pip install awscli
            aws --version
     - run:
          name: Build application Docker image
          command: |
            docker build -t app .
     - deploy:
           name: Push application Docker image
           command: |
              chmod +x deploy.sh
              ./deploy.sh