version: 2
general:
  artifacts:
     - coverage/lcov-report
  branches:
    only:
     - master
     - istanbuljs


jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
     - checkout
     - run: npm install
     - run: npm test