version: 2
general:
  branches:
    only:
     - master
     - istanbuljs


jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
     - checkout
     - run: npm install
     - run: npm test
     - run:
        name: Creating Dummy Artifacts
        command: |
             mkdir /tmp/coverage
             cp ./coverage.* /tmp/coverage
     - store_artifacts:
         path: /tmp/coverage