version: 2
general:
  branches:
    only:
     - master
     - istanbuljs


jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
     - checkout
     - run: npm install
     - run: npm test
     - run:
         name: Creating Dummy Artifacts
         command: |
           echo "my artifact file" > /tmp/artifact-1;
           mkdir /tmp/artifacts;
           echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

     - store_artifacts:
         path: /tmp/artifact-1
         destination: artifact-file

     - store_artifacts:
         path: /tmp/artifacts